CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_STUDIO=y

# Add battery reporting for second half
# https://zmk.dev/docs/config/battery#peripheral-battery-monitoring
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Low power states
# https://zmk.dev/docs/config/power
CONFIG_ZMK_SLEEP=y
# Default value (30 seconds)
# CONFIG_ZMK_IDLE_TIMEOUT=30000
# Default value (15 min)
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
